# _config.yml
title: "Mon e-commerce de T-shirts"
description: "Achetez des T-shirts stylés ici !"
baseurl: ""  # Laissez vide pour une racine
url: "https://jeevapathai-store.firebaseapp.com/"  # URL de votre site Firebase Hosting

collections:
  products:
    output: true  # Active la génération des pages produit

defaults:
  - scope:
      path: "_products"
    values:
      layout: "product"  # Utiliser le layout product pour les pages produits
