- name: Product 1
  price: 29.99
  description: A description of Product 1.
  image: "/assets/images/product1.jpg"
  
- name: Product 2
  price: 19.99
  description: A description of Product 2.
  image: "/assets/images/product2.jpg"
  
- name: Product 3
  price: 39.99
  description: A description of Product 3.
  image: "/assets/images/product3.jpg"
  
- name: Product 4
  price: 49.99
  description: A description of Product 4.
  image: "/assets/images/product4.jpg"
  
- name: Product 5
  price: 59.99
  description: A description of Product 5.
  image: "/assets/images/product5.jpg"
